### ISSUE TITLE
1.1.0

### ISSUE THREAD

**Issue by ono** [c-rack/cidr-elixir#45]
Hello. Is there any reason you hesitate to release 1.1.0? [Changelog](https://github.com/c-rack/cidr-elixir/blob/master/CHANGELOG.md) says there is 1.1.0 but it's not listed on hex.

https://hex.pm/packages/cidr

Would also be nice to see https://github.com/c-rack/cidr-elixir/pull/44 too.

**Comment by c-rack** [comment]
@ono will release a new version shortly, thanks for the reminder!

**Comment by ono** [comment]
awesome! thanks 👍

**Comment by duijf** [comment]
@c-rack 1.1.0 isn't on Hex at this moment, right? Bumping this :)

**Comment by c-rack** [comment]
You are right, thanks for the reminder, I'll put it on my todo list.

**Comment by c-rack** [comment]
Published: https://hex.pm/packages/cidr/1.1.0
