### ISSUE TITLE
match/2 needs better error handling

### ISSUE THREAD

**Issue by duijf** [c-rack/cidr-elixir#5]
Currently, match just returns `true` or `false`. However, it would be good to let callers know if there is an error in the ip-address they passed in. Currently `CIDR.match(cidr, :test)` returns `false`, but `CIDR.match(cidr, "this should be an ip address")` throws a matcherror.

You can also pass in any 4 or 6 tuple and there will not be any validation.

The way I see it, we can pick from two approaches:

Tagged tuples:
- When it's a match: `{:ok, true}`
- When it's not a match: `{:ok, false}`
- When the IP to match against is invalid: `{:error, reason}`.

Exceptions:
- When it's a match: `true`
- When it's not a match: `false`
- When the IP to match against is invalid: `raise ArgumentError`.

We can also support both, separate by function name: `match` for the first interface and `match!` for the second.

@c-rack what do you think?

**Comment by c-rack** [comment]
Great idea! Any PRs implementing this are welcome!

**Comment by duijf** [comment]
Implemented in #6.
