### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ifoo** [c-rack/cidr-elixir#52]
Thank you for merging #51 !
It would be nice if you could bump the version number, so we could get a new release on hex, without having to explicitly reference master. Last release was from 2017 as far as I can tell.

**Comment by ckruse** [comment]
This would be very much appreciated

**Comment by jamilbk** [comment]
@c-rack Agreed -- new release would be great!

**Comment by duijf** [comment]
I would also like to make a new release, given the community is still interested in this library.

I reached out to @c-rack over email whether he'd be open to granting me Hex.pm push rights

**Comment by gitneko** [comment]
@c-rack Hi, what is the status? Could you please release a new version? Would be much appreciated.

**Comment by c-rack** [comment]
@gitneko @duijf @jamilbk @ckruse @ifoo 
https://hex.pm/packages/cidr/1.2.0

Sorry for any inconvenience.

Please feel free to send PR for the changelog or fixing some of the deprecating warnings...
